test: &default

  # Credentials for REST APIs
  client_id: Ad4RtBC51ZEMVfNBvw4oDuPGBE_0unMiKb33WHEkgdVrycDdw9HKZ31vFAoW
  client_secret: EL4J8xANXkzdHVMzyE8KjfEpodTx2aJuIyJAi54mhAf48oFoEdGrYA7_3POf

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: thanhkhoait-facilitator_api1.gmail.com
  password: 1396490481
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AbW0SY.CwpBJwk6bkBuNNmABU9Wg 
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default